### ISSUE TITLE
E-Persons should be encoded with UTF-8

### ISSUE THREAD

**Issue by kmcelwee** [pulibrary/dspace-development#275]
Researchers with accents in their names are bungled.  See Bo Honore: `HonorÃ© `

**Comment by kmcelwee** [comment]
This was manually corrected. The high ID # suggests that this researcher logged in through Shibboleth, meaning this error could have occurred anywhere among the many handoffs between dataspace and shibboleth. Thankfully it can be corrected in Dataspace. Putting this in the icebox, since there is a manual solution when necessary. But according to Atmire, there is no straightforward solution.

**Comment by matthewjchandler** [comment]
The submitter who prompted this issue was still seeing his name displayed incorrectly in the system as of 2021-02-03 at 5:30 pm:
![Character encoding error](https://user-images.githubusercontent.com/66128387/106896639-d8fa4880-66bf-11eb-8f80-a5ff996c7ec2.jpg)

**Comment by matthewjchandler** [comment]
I saw a difference on my side of things, where Bo's name was listed in my pool: it looked corrected just after 4:00 PM on 2021-02-04

**Comment by kmcelwee** [comment]
At approximately 10am today, I fixed Bo's name. I expect that, were he to log in again, Shibboleth would overwrite. I intend to elevate this issue to Atmire.

**Comment by kelynch** [comment]
We discussed this with Atmire today; I'm going to examine the headers of the login request to see if data we're getting from Shibboleth already has the botched encoding, or if we're botching the encoding when we save/store the user's name.

**Comment by hhkitsune** [comment]
Closed for now due to lack of test case. Write new ticket if this happens again.
